Repository prospector-dev/prospector, pull requests merged in 2022-12, with the labels that each got.

#548 Fix merge issue with file finding (fix #547)
  prospector/tools/pylint/linter.py
Labels: bug

#549 Release 1.8.2
  CHANGELOG.rst
  pyproject.toml
Labels: documentation

#552 Fix undefined name sre_constants in Python 3.11
  prospector/config/__init__.py
  prospector/tools/profile_validator/__init__.py
Labels: enhancement

#553 pyproject.toml: Upgrade tool.poetry.dev-dependencies
  poetry.lock
  pyproject.toml
Labels: enhancement

#554 pre-commit autoupdate && pre-commit run --all-files
  .pre-commit-config.yaml
Labels: enhancement

#559 Downgrade poetry to permit extra option with underscores
  .github/workflows/release.yml
Labels: bug

#555 Fix re._constants again
  prospector/config/__init__.py
  prospector/tools/profile_validator/__init__.py
Labels: enhancement
