Repository prospector-dev/prospector, pull requests merged in 2024-10, with the labels that each got.

#645 update some dependency pins so we can build with Python=3.12
  .github/workflows/tests.yml
  poetry.lock
  pyproject.toml
Labels: dependencies

#668 Add python 3.13 to the test matrice
  .github/workflows/tests.yml
  pyproject.toml
Labels: enhancement, dependencies

#669 Upgrade pre-commit hooks
  .pre-commit-config.yaml
  prospector/exceptions.py
  prospector/formatters/pylint.py
  prospector/formatters/vscode.py
  prospector/formatters/xunit.py
  prospector/suppression.py
  prospector/tools/pylint/__init__.py
  tests/execution/test_execution.py
Labels: dependencies

#642 Limit pylint to <3 while waiting for a new release of ``requirements-detector``
  CHANGELOG.rst
  poetry.lock
  pyproject.toml
Labels: enhancement

#629 MyPy: Add the `check-untyped-defs` option for mypy.
  docs/profiles.rst
  prospector/tools/mypy/__init__.py
Labels: enhancement
